### ISSUE TITLE
Implement unit tests for client and transfers

### ISSUE THREAD

**Issue by bermannoah** [WeTransfer/wetransfer_ruby_sdk#11]
At the moment we have one majestic suite of integration tests. Help us out by implementing unit tests! One potentially interesting thing here is that the integration tests rely on actual API calls - but doing real-live-calls for every test suite run is less than ideal. If you love test mocks this is the issue for you! (Or maybe you've got some other solution you'd like to add?)

**Comment by davidenko87** [comment]
I think with the latest release we have covered almost everything with tests
