### ISSUE TITLE
Add simplest use case possible for Transfer

### ISSUE THREAD

**Issue by arnoFleming** [WeTransfer/wetransfer_ruby_sdk#36]
In order to make adoption as easy as possible, it would make sense to have the simplest use case available to tramsfer using the ruby sdk

The steps involved could be

1. create upload client
    * add all files to the transfer
2. tell the client to finish the transfer (in its own time)
3. the API returns the url that _eventually_ holds the completed transfet

**Comment by davidenko87** [comment]
Progress can be followed here: https://github.com/WeTransfer/wetransfer_ruby_sdk/pull/38
